/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0e8c2f64-6b45-44ba-b5a6-cf89c70a695b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bYpC6Al4t",
    "aws_user_pools_web_client_id": "7udchnl2dep6nvfu90rlcgslji",
    "oauth": {},
    "predictions": {
        "identify": {
            "identifyText": {
                "proxy": false,
                "region": "us-east-1",
                "defaults": {
                    "format": "ALL"
                }
            }
        }
    }
};


export default awsmobile;
